name: Auto Build

on:
  workflow_dispatch:
    inputs:
      CreateRelease:
        description: 'Do you want to create a release?'
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Unbound Static
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Check & Build Unbound
      id: build_release
      run: |
        bash build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unbound-static
        path: build_out/*

    - name: Create release
      if: inputs.CreateRelease == 'true'
      id: create_release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: unbound-${{ env.unbound_version }}
        allowUpdates: true
        tag: ${{ env.unbound_version }}
        commit: master
        replacesArtifacts: true
        token: ${{ secrets.workflow_token }}
        artifacts: build_out/*
